server:
  port: 9090
#  servlet:
#    context-path: /aiProxy

spring:
  jpa:
    hibernate:
      ddl-auto: update  # 数据库表结构自动更新
    show-sql: true      # 显示SQL语句
    properties:
      hibernate:
        format_sql: true  # 格式化SQL语句输出

  datasource:
    url: jdbc:postgresql://localhost:5432/chat_ai  # PostgreSQL数据库连接URL
    username: postgres                             # 数据库用户名
    password: postgres                             # 数据库密码
    driver-class-name: org.postgresql.Driver      # 数据库驱动
    hikari:  # 数据库连接池配置
      maximum-pool-size: 10  # 最大连接数
      minimum-idle: 2        # 最小空闲连接数
      idle-timeout: 30000    # 空闲连接超时时间（30秒）
      max-lifetime: 1800000  # 连接最大生命周期（30分钟）

  data:
    redis:
      host: localhost    # Redis服务器地址
      port: 6379        # Redis端口
      password: redis   # Redis密码
      database: 0       # Redis数据库索引
      lettuce:
        pool:
          max-active: 8   # 最大连接数
          max-wait: -1    # 最大等待时间（-1表示无限等待）
          max-idle: 8     # 最大空闲连接数
          min-idle: 0     # 最小空闲连接数

  servlet:
    multipart:
      max-file-size: 10MB      # 单个文件最大大小
      max-request-size: 10MB   # 请求最大大小

  ai:
    zhipuai:
      api-key: ${ZHIPU_AI_API_KEY}
      chat:
        options:
          model: glm-4-flash        # 使用的AI模型
          temperature: 0.7          # 模型温度参数（控制输出的随机性）
          top_p: 0.9                # 采样概率阈值
          max_tokens: 10000         # 生成的最大令牌数


app:
  jwt-secret: YYvJvguytDSwVei71yrAlBE4UFwZRwWh+WFylCTK8RXY2kxFzNHfkVCpi9oeYyZIDKUsjGQ35ASx08yssmWffQ==
  jwt-expiration-milliseconds: 86400000 # 24 hours